version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "dbGraphQL"
    ports:
      - "3306:3306"
    volumes:
      - C:\app\teste:/var/lib/mysql
    networks:
      - mysql-compose-network
networks:
  mysql-compose-network:
    driver: bridge